import React from 'react';

const SolutionsSection = () => {
  const solutions = [
    {
      image: "images/geofence.png",
      title: "Geofencing and GPS Precision",
      description: "Every driver route, site visit, and fluid transfer is geotagged and timestamped using high-accuracy GPS."
    },
    {
      image: "images/bluetooth.png",
      title: "Bluetooth Flow Meter Automation",
      description: "By integrating directly with Bluetooth-enabled flow meters, the app captures accurate volume readings at both pickup and disposal points."
    },
    {
      image: "images/realtime.png",
      title: "Real-Time Well Verification",
      description: "The application cross-references each injection site against an up-to-date database of permitted wells."
    },
    {
      image: "images/automated_uic.png",
      title: "Automated UIC Generation",
      description: "UIC documentation is automatically generated by combining flow data, GPS tracks, operator ID, and digital signature."
    },
    {
      image: "images/digital_custody_chain.png",
      title: "Digital Chain of Custody",
      description: "Immutable audit logs record every step in the transportation and disposal chain — from fluid origin to well injection — including who handled it, when, where, and how."
    }
  ];

  return (
    <section className="solutions-section">
      <div className="solutions-grid-overlay"></div>
      <div className="container">
        <div className="section-header">
          <div className="section-badge">Built to Solve Real Field Problems</div>
          <h2 className="section-title">
            Explore More <span className="gradient-text">Smart Solutions</span>
          </h2>
          <p className="section-description">
            Discover our complete suite of AI-powered solutions designed to transform every
            aspect of energy operations with intelligence and precision.
          </p>
        </div>
        
        <div className="solutions-grid">
          {solutions.map((solution, index) => (
            <div key={index} className="solution-card">
              <div className="card-image">
                <img src={solution.image} alt={solution.title} />
                <div className="external-link-icon">
                  <svg viewBox="0 0 14 14" fill="none">
                    <path className="icon-external-link" d="M8.75 1.75H12.25V5.25" strokeWidth="1.16667"/>
                    <path className="icon-external-link" d="M5.8335 8.16667L12.2502 1.75" strokeWidth="1.16667"/>
                    <path className="icon-external-link" d="M10.5 7.58333V11.0833C10.5 11.3928 10.3771 11.6895 10.1583 11.9083C9.9395 12.1271 9.64275 12.25 9.33333 12.25H2.91667C2.60725 12.25 2.3105 12.1271 2.09171 11.9083C1.87292 11.6895 1.75 11.3928 1.75 11.0833V4.66667C1.75 4.35725 1.87292 4.0605 2.09171 3.84171C2.3105 3.62292 2.60725 3.5 2.91667 3.5H6.41667" strokeWidth="1.16667"/>
                  </svg>
                </div>
              </div>
              
              <div className="card-content">
                <h3 className="card-title">{solution.title}</h3>
                <p className="card-description">{solution.description}</p>
                
                <div className="learn-more">
                  <span>Learn More</span>
                  <svg viewBox="0 0 14 15" fill="none">
                    <path className="icon-external-link" d="M2.9165 7.81006H11.0832" strokeWidth="1.16667"/>
                    <path className="icon-external-link" d="M7 3.72681L11.0833 7.81014L7 11.8935" strokeWidth="1.16667"/>
                  </svg>
                </div>
              </div>
            </div>
          ))}
        </div>
        
        <div className="solutions-pagination">
          <div className="pagination-dots">
            <div className="dot active"></div>
            <div className="dot"></div>
          </div>
          
          <button className="btn btn-primary">View All Solutions</button>
        </div>
      </div>
    </section>
  );
};

export default SolutionsSection;
